In [2]:
# Imports
import numpy as np
import pandas as pd

In [3]:
# Importando o dataset
df = pd.read_csv("dataset.csv", index_col=0)

In [4]:
df.shape

(40, 49)

In [5]:
df.head()

186          295          321          337  \
NSCLC_A549_1   171210.5829  1246686.524  527193.4870  411155.8781   
NSCLC_H1703_2  204751.3591  1338013.461  571379.0841  486137.0920   
NSCLC_H1703_1  203558.4952  1040438.105  498460.6875  411052.8868   
NSCLC_A549_2   245859.2006  1371135.588  153050.9373  495539.7034   
NSCLC_H1437_1  214448.1780  1107105.986  524333.5670  484994.8797   

                       464          469          502          506  \
NSCLC_A549_1   59929.70461  49255.07973  171273.1364  159183.1286   
NSCLC_H1703_2  89261.66256  72052.72202  187464.2389  180000.6140   
NSCLC_H1703_1  96002.36973      0.00000  193894.4078  179518.9387   
NSCLC_A549_2   81436.65785  85158.56741       0.0000  186757.1440   
NSCLC_H1437_1  92368.82235  69868.54980  181168.8533       0.0000   

                       563           931  ...          1401          1402  \
NSCLC_A549_1   663694.9741   35070.49713  ...   95049.95991  1.719464e+06   
NSCLC_H1703_2  443440.3745   89938.26439  ...  131002.12740  8.290090e+05   
NSCLC_H1703_1  736672.9068  107041.34120  ...  108827.84800  8.541730e+05   
NSCLC_A549_2   809830.2341   43565.82607  ...  106003.59820  2.037000e+06   
NSCLC_H1437_1  635990.2172   51087.42828  ...   83218.09256  1.269266e+06   

                      1414          1422         1524          1551  \
NSCLC_A549_1   645473.1920   89954.00002  52983.82193  1.672322e+06   
NSCLC_H1703_2  293504.7109   42264.73772  97472.88420  1.608167e+06   
NSCLC_H1703_1  313811.6234   51125.12753  95633.56928  1.931491e+06   
NSCLC_A549_2   762600.1361  116878.29910  58497.52991  2.077164e+06   
NSCLC_H1437_1  459612.8875   64837.50435      0.00000  9.434720e+05   

                       1553         1559          1561          1568  
NSCLC_A549_1   6.867305e+05  259889.4715  1.563879e+06  189971.51110  
NSCLC_H1703_2  9.408252e+05  363398.5823  3.043114e+05   35762.79339  
NSCLC_H1703_1  1.086556e+06  417606.0810  4.365568e+05   53865.65208  
NSCLC_A549_2   8.461167e+05  328548.1739  1.824857e+06  243842.05260  
NSCLC_H1437_1  4.022300e+05  153070.9443  3.745915e+05   44104.41364  

[5 rows x 49 columns]

In [6]:
df_matriz = df.to_numpy()
df_matriz

array([[ 171210.5829 , 1246686.524  ,  527193.487  , ...,  259889.4715 ,
        1563879.456  ,  189971.5111 ],
       [ 204751.3591 , 1338013.461  ,  571379.0841 , ...,  363398.5823 ,
         304311.3998 ,   35762.79339],
       [ 203558.4952 , 1040438.105  ,  498460.6875 , ...,  417606.081  ,
         436556.8065 ,   53865.65208],
       ...,
       [ 204221.0677 , 1278411.147  ,  566328.7108 , ...,  148904.9146 ,
         708831.1396 ,  121367.7799 ],
       [ 175149.2572 , 1101994.558  ,  175843.386  , ...,  144382.0813 ,
          77809.90877,  287232.319  ],
       [ 225370.32   , 1407596.388  ,       0.     , ...,  115385.9564 ,
          61827.40414,  176777.0753 ]])

In [7]:
df_matriz.shape

(40, 49)

In [10]:
np.mean(df_matriz, axis=0)

array([ 185011.885065  , 1154726.1125125 ,  476459.903455  ,
        449787.4246325 ,   86856.29951125,   72130.97627625,
        176979.6677525 ,  166611.20674   ,  449567.59509   ,
         52692.907637  ,  226424.793347  ,   62663.96099525,
        138339.773075  ,  129471.267691  , 1019795.859975  ,
        721338.803799  ,  227841.588217  ,  616851.856213  ,
        136489.74543125,  192610.57603225, 1627980.86294   ,
        587584.20022   ,  364438.0159675 ,  230686.86434   ,
        308633.94730675,  207669.33142927,  883422.149645  ,
        308494.23104575, 1898308.83055   ,  686983.593885  ,
         92755.30828475,  105912.44276475,  117400.5695485 ,
        668102.95982125,   90620.6922405 ,  465681.176975  ,
        168326.3644965 , 1312030.034055  ,  485060.6826275 ,
         69987.10878275, 1845806.137775  ,  733104.9163575 ,
        100761.58881   ,   88273.41699825,  606441.2117655 ,
        374514.221095  ,  140542.7518785 ,  478166.55993875,
         97350.59901   ]

In [11]:
# Função com implementação do algoritmo PCA
def PCA(input):
    
    mean = np.mean(input, axis= 0)
    
    # Subtraindo a média da matriz de entrada original
    normalised_input = np.subtract(input, mean)
    
    # matriz de covariância
    cov_mat = np.cov(normalised_input, rowvar= False)
    
    # Localizando autovalores and autovetores
    value, vector = np.linalg.eig(np.array(cov_mat))
    
    # Ordenando os autovetores de acordo com os autovalores
    index = value.argsort()[::-1]
    eigen_value = value[index]
    prin_component = vector[:,index]
    
    # Multiplicando matriz de componente principal com a matriz de dados de entrada para obter o PCA
    pca_output = np.dot(normalised_input, prin_component)

    return pca_output, eigen_value, prin_component, cov_mat

In [12]:
pca_out, eigenval_v1, principal_component, cov_matrix = PCA(df_matriz)

In [13]:
# Somando as 10 primeiras variaveis 
variancia_explicada_v1 = (eigenval_v1[0] / sum(eigenval_v1)) + \
                         (eigenval_v1[1] / sum(eigenval_v1)) + \
                         (eigenval_v1[2] / sum(eigenval_v1)) + \
                         (eigenval_v1[3] / sum(eigenval_v1)) + \
                         (eigenval_v1[4] / sum(eigenval_v1)) + \
                         (eigenval_v1[5] / sum(eigenval_v1)) + \
                         (eigenval_v1[6] / sum(eigenval_v1)) + \
                         (eigenval_v1[7] / sum(eigenval_v1)) + \
                         (eigenval_v1[8] / sum(eigenval_v1)) + \
                         (eigenval_v1[9] / sum(eigenval_v1)) 

In [14]:
# Convertendo para valor percentual
variancia_explicada_percentual = variancia_explicada_v1 * 100

In [15]:
print("Total de Variância dos Dados Explicada Por 10 Componentes Principais:", variancia_explicada_percentual)

Total de Variância dos Dados Explicada Por 10 Componentes Principais: (95.7835020418579+0j)


In [ ]:
# Calculando a variância total
total_variance_v1 = sum(eigenval_v1)
total_variance_v1

(3358556479843.022+0j)

In [22]:
# Calculando a variância explicada por cada componente principal
variance_explained_v1 = [(i / total_variance_v1) for i in eigenval_v1]


In [21]:
cumulative_variance_explained_v1 = np.cumsum(variance_explained_v1)


In [19]:
# Exibindo a variância explicada por cada um dos 10 primeiros componentes principais
variance_explained_v1[:10]

[(0.4006389994390442+0j),
 (0.14908971340570948+0j),
 (0.12996709872406506+0j),
 (0.09534871230146738+0j),
 (0.06440429234620802+0j),
 (0.03814704235755977+0j),
 (0.028828684990927937+0j),
 (0.022276999290681034+0j),
 (0.016360170455751766+0j),
 (0.012773307107164409+0j)]

In [20]:
# Exibindo a variância acumulada dos 10 primeiros componentes principais
cumulative_variance_explained_v1[:10]

array([0.400639  +0.j, 0.54972871+0.j, 0.67969581+0.j, 0.77504452+0.j,
       0.83944882+0.j, 0.87759586+0.j, 0.90642454+0.j, 0.92870154+0.j,
       0.94506171+0.j, 0.95783502+0.j])

# implementação com o Sklearn

In [23]:
import sklearn
from sklearn.decomposition import PCA

In [24]:
# Aplicando PCA
pca = PCA(n_components = 10)
X_pca = pca.fit_transform(df_matriz)

In [25]:
# Variância explicada por cada componente
variance_explained_v3 = pca.explained_variance_

In [26]:
# Proporção da variância explicada por cada componente
variance_explained_v3_ratio = pca.explained_variance_ratio_

In [27]:
# Variância explicada acumulada
cumulative_variance_v3_ratio = np.cumsum(variance_explained_v3_ratio)

In [28]:
print("Proporção da variância explicada por cada componente:\n\n", variance_explained_v3_ratio)

Proporção da variância explicada por cada componente:

 [0.400639   0.14908971 0.1299671  0.09534871 0.06440429 0.03814704
 0.02882868 0.022277   0.01636017 0.01277331]


In [29]:
print("Variância explicada acumulada:\n\n", cumulative_variance_v3_ratio)

Variância explicada acumulada:

 [0.400639   0.54972871 0.67969581 0.77504452 0.83944882 0.87759586
 0.90642454 0.92870154 0.94506171 0.95783502]
